/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C_Master.h"
#include "I2C_Master_I2C.h"
#include "I2C_Master_PINS.h"
#include "I2C_Master_I2C_PVT.h"
#include "I2C_Master_PVT.h"
#include "I2C_Master_BOOT.h"
#include "LED_Conect.h"
#include "LED_Conect_aliases.h"
#include "ADC_Sensing.h"
#include "ADC_Configuration.h"
#include "ADC_Adc.h"
#include "ADC_Structure.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "Servo.h"
#include "Servo_aliases.h"
#include "Clock_Servo.h"
#include "PWM_Servo.h"
#include "Button.h"
#include "Button_aliases.h"
#include "Button_INT.h"
#include "Clock_Buzzer.h"
#include "PWM_Buzzer.h"
#include "Buzzer.h"
#include "Buzzer_aliases.h"
#include "I2C_Master_SCBCLK.h"
#include "I2C_Master_sda.h"
#include "I2C_Master_sda_aliases.h"
#include "I2C_Master_scl.h"
#include "I2C_Master_scl_aliases.h"
#include "I2C_Master_SCB_IRQ.h"
#include "ADC_ISR.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "cy_em_eeprom.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"

/*[]*/

